# dot product

In [2]:
import numpy as np

w = np.array([2,2])
x = np.array([2,2])
dot = np.dot(w,x)
dot

np.int64(8)

# normal distribution

In [3]:
random =np.random.seed(42)
random_normal = np.random.randn(3)
random_normal

array([ 0.49671415, -0.1382643 ,  0.64768854])

In [4]:
random = np.random.rand(3)
random

array([0.15601864, 0.15599452, 0.05808361])

# concatenation

In [5]:
import pandas as pd
data = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,0,0,1]
}

AND = pd.DataFrame(data)

AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [6]:
X = AND.drop("y", axis=1)
y = AND["y"]
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [7]:
X.shape
len(X)

4

In [11]:
bias = np.c_[X, -np.ones(len(X))]  # Adding a column of ones for the bias term
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])